### ISSUE TITLE
Hello, how to use it?

### ISSUE THREAD

**Issue by exiawsh** [karljans/ros-pycam#1]
If I know the gstreamer str?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by karljans** [comment]
Hi, 
Sorry, the project is still very new, just got it working a couple of days ago. I now added some documentation, which should help you get started.

To answer your question, you can pass the GStreamer pipeline string to the driver by adding the `gst_pipeline` parameter to the node in your launch file, like this:
`<param name="gst_pipeline" value="your_pipeline_string_here"/>`

**Comment by exiawsh** [comment]
> Hi, Sorry, the project is still very new, just got it working a couple of days ago. I now added some documentation, which should help you get started.
> 
> To answer your question, you can pass the GStreamer pipeline string to the driver by adding the `gst_pipeline` parameter to the node in your launch file, like this: `<param name="gst_pipeline" value="your_pipeline_string_here"/>`

**Comment by exiawsh** [comment]
Thank you for your reply!But yesterday,I tried this and failed, is there something wrong?
      "nvv4l2camerasrc device=/dev/video{camera_id} do-timestamp=true ! \
        queue max-size-buffers=0 max-size-time=0 max-size-bytes=0 max-size-bytes=65536 ! \
        video/x-raw(memory:NVMM), width=(int){capture_width}, height=(int){capture_height}, \
        framerate=(fraction){framerate}/1 ! \
        nvvidconv flip-method={flip_method} ! \
        video/x-raw,  format=(string)NV12, width=(int){display_width}, height=(int){display_height} ! \
        videoconvert ! \
        appsink "

**Comment by karljans** [comment]
What is the error that you are getting?

I don't have access to a Jetson device with ROS installed currently to test your pipeline, but it seems way too complicated. Does it work when you just run it at terminal using `gst-launch-1.0` at terminal?

Also, take a look at this file.
[https://github.com/JetsonHacksNano/CSI-Camera/blob/master/simple_camera.py](https://github.com/JetsonHacksNano/CSI-Camera/blob/master/simple_camera.py)
